# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEWuntitled2K_125.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1894, 947)
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tubiao_1_1/tubiao.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#MainWindow {background-image: url(:/beijing_2_2/3.jpeg);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 50, 1331, 831))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    \n"
"\n"
"    color: #ffffff;\n"
"    border-style: outset;\n"
"   \n"
"    \n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #ffffff;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 900, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(940, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("QRadioButton{\n"
"\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.radioButton_6.setObjectName("radioButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 210, 461, 331))
        self.label.setText("")
        self.label.setObjectName("label")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(840, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("QRadioButton{\n"
"\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(1040, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setStyleSheet("QRadioButton{\n"
"\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(540, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setStyleSheet("QRadioButton{\n"
"\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(640, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setStyleSheet("QRadioButton{\n"
"\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_11.setGeometry(QtCore.QRect(740, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setStyleSheet("QRadioButton{\n"
"\n"
"color:#ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.radioButton_11.setObjectName("radioButton_11")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 570, 461, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"\n"
"    color: #ffffff;\n"
"\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 70, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"color:#ffffff;\n"
"\n"
"background-color:#cb0000\n"
"}\n"
"QPushButton:hover{\n"
"color:#0d0d0d;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 70, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"color:#ffffff;\n"
"\n"
"background-color:#cb0000\n"
"}\n"
"QPushButton:hover{\n"
"color:#0d0d0d;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(360, 70, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"color:#ffffff;\n"
"\n"
"background-color:#cb0000\n"
"}\n"
"QPushButton:hover{\n"
"color:#0d0d0d;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WCQ QT抽奖活动"))
        self.radioButton_6.setText(_translate("MainWindow", "五等奖"))
        self.radioButton_7.setText(_translate("MainWindow", "四等奖"))
        self.radioButton_8.setText(_translate("MainWindow", "六等奖"))
        self.radioButton_9.setText(_translate("MainWindow", "一等奖"))
        self.radioButton_10.setText(_translate("MainWindow", "二等奖"))
        self.radioButton_11.setText(_translate("MainWindow", "三等奖"))
        self.pushButton_7.setText(_translate("MainWindow", "开始"))
        self.pushButton_8.setText(_translate("MainWindow", "停止"))
        self.pushButton_10.setText(_translate("MainWindow", "重置"))
import beijing_2_rc
import jp_1_rc
import tubiao_1_rc
